### ISSUE TITLE
Minimum gnome-shell version

### ISSUE THREAD

**Issue by mozky** [fffilo/gnome-vagrant-indicator#2]
Hi, first of all thank you for the great extension, I've been using it on a system with Ubuntu 17.04 with no problems at all, but I'm trying to install the extension on a **Ubuntu 16.10 with gnome-shell version 3.20.4** but it says my gnome-version is not compatible.

I've already tried to 'disable-extension-version-validation' which let me install the extension but when using it it doesn't seem to work correctly, since I can't get any command to work (SHH, halt, Open in Terminal, etc).

So which is the minimum gnome-version required for the extension to work? So I can get into updating gnome and see if it helps.

Thanks a bunch!

**Comment by fffilo** [comment]
i haven't test it on any other version than my `GNOME Shell 3.18.5`. i'll will test it when i find some time...

**Comment by mozky** [comment]
Cool, hit me up if you need any logs or something for 3.20.4

**Comment by fffilo** [comment]
i tried on ubutnu 16.04 with gnome 3.20.4 and everything works as expected. the problem is not in version but somewhere else. please open terminal, paste 

     journalctl /usr/lib/gnome-session/gnome-session-binary -f -o cat | grep gnome-vagrant-indicator

...and refresh gnome (alt+f2 r). the terminal should output extension errors, so please paste it here.

thnx.

**Comment by mozky** [comment]
Found the issue, I have my x-terminal-emulator set to gnome-terminator, so the plugin wont run the terminal commands, changing to gnome-terminal and it works, any hints on how to get it to work with gnome-terminator?

**Comment by fffilo** [comment]
upgrade exension

    wget https://raw.githubusercontent.com/fffilo/gnome-vagrant-indicator/master/install.sh -O - | sh

and set newly added 'terminal emulator' option in preferences

![screenshot from 2017-09-04 22-56-39](https://user-images.githubusercontent.com/985352/30038403-6b01b594-91c4-11e7-8f5f-40bd2abfee4b.png)

**Comment by mozky** [comment]
Awesome! Got it working, thanks man @fffilo

**Comment by fffilo** [comment]
hi there again @mozky.

i'm doing complete code refactoring and decided to remove _terminal emulator_ option from preferences. i think it would be best not to let user to manually add path here. and since other system commands (_open in file manager_ and _edit vagrantfile_) use default applications to open them, _open in terminal_ should act the same.

so, before merge this feature in master, please test if this works for you. i tested it with _terminator_, _gnome-terminal_, _koi8rxterm_, _lxterm_, _uxterm_ and _xterm_  (`update-alternatives --config  x-terminal-emulator`) and everything works as expected. just wanted your 'approval' before continuing ;-)

please update your extension...

    wget https://raw.githubusercontent.com/fffilo/gnome-vagrant-indicator/master/install.sh -O - | bash -s -- develop

...test it and let me know.

you can always revert your changes with...

    wget https://raw.githubusercontent.com/fffilo/gnome-vagrant-indicator/master/install.sh -O - | bash

thank you very much!

**Comment by mozky** [comment]
Hey @fffilo,

Just tested the new version and I can confirm that it works with terminator, so I would say you are ready to go!

Thanks for this great extension!

**Comment by fffilo** [comment]
No, thank you!
